### ISSUE TITLE
Trying to sync when not logged in

### ISSUE THREAD

**Issue by krokofant** [stuartcryan/lastpass-alfred-workflow#23]
Sometimes when I'm gonna use this workflow I have been logged off. I don't know why.

**But to the point.**
Because of this I just try to _lp apple_ to get my apple login but I'm not logged in.

The workflow then tries to sync and fetch the matched accounts but it cannot.

<img width="546" alt="Syncing" src="https://cloud.githubusercontent.com/assets/5908498/13590336/507a0a20-e4df-11e5-863e-3b84da956469.png">

The solution for me is then to _lplogin_ and then _lp apple_ again.

I tried to reproduce this by logging off and then lp apple but then it clearly identifies me as logged off.

### I might be mad
The appearing offline thing happens most times when I'm gonna use this workflow which is pretty seldom. It doesn't behave the same way as it would if I log off manually. To troubleshoot this further when it happens, I assume I'd just activate the debug console and check what happens?

**Comment by krokofant** [comment]
I tried to reproduce this by logging off and then _lp apple_ but then it clearly identifies me as logged off.

**Comment by stuartcryan** [comment]
Hmmm I have seen this before but wasn't sure if I was just loosing my mind or was actually a problem.

I will have a look and see what I can come up with.
Cheers,
Stuart

**Comment by krokofant** [comment]
Reproduce
```
lpsettimeout 10
lplogin
lp github
```
wait 10 seconds
`lp github`

**Comment by krokofant** [comment]
My idea is that this code
```
my ($results, $err, $errorCode) = capture {
    system($lpass_exec . ' ls --sync=no | grep -i "' . $search . '"');
};
```
is running `lpass ls --sync=no` which when executed via Terminal (not Alfred) and you're not logged in prompts for the Master password, just like the one you have _passwordInput.osascript_. If executed in a Terminal the prompt displays correctly but when executed via the workflow (Alfred -> perl5.18 -> sh -> lpass) it doesn't display the prompt.

It then just lays in the background and each lp query you do you're spawing a new process (Alfred -> perl5.18 -> sh -> lpass).

**Comment by stuartcryan** [comment]
All righty :) 

Done some work on this can you please give this a go https://dl.dropboxusercontent.com/u/9093155/LastPass%20CLI_1.4.5_beta.alfredworkflow

Only caveat is that I currently haven't figured out a reliable way to test IF lastpass has timed out or not, which means I cant test for this, store what you have typed and re-load the search screen once you are logged in...

Let me know how this goes as a start and I will see what else I can come up with you handle it more completely.

Cheers,
Stuart

**Comment by krokofant** [comment]
That is much better then the previous version as you actually get somewhere.

Great! :)

**Comment by stuartcryan** [comment]
Hmmm, noted, let me work on it over the next week , the cancel should properly terminate it. Will keep you posted with another beta version as soon as I can.

**Comment by stuartcryan** [comment]
All righty, can you please give this version a go https://dl.dropboxusercontent.com/u/9093155/LastPass%20CLI_1.4.5_beta2.alfredworkflow

Major change is I have come up for a creative solution for actually testing if you are logged in or not, this is how I always intended this to be handled. So you can now kick it off using ctrl + enter to log in if you are not already.

This is not to say that I won't enhance it a bit more in future. I would like (if possible) to store and retrieve what you were searching for to make it a little more user friendly.

Please let me know your thoughts.
Cheers,
Stuart

**Comment by krokofant** [comment]
I like it. It looks alot better with the ctrl+enter to login. But the infinite loop is still there albeit with a little bit more time between the popups.

I.E. The cancel still does not work.

**Comment by stuartcryan** [comment]
Awesome on the first front and *puzzled* on the second. I tested this numerous times on my system and it works as expected. I will do some more debugging and see what I can come up with.

**Comment by stuartcryan** [comment]
All righty, how about this --> https://dl.dropboxusercontent.com/u/9093155/LastPass%20CLI_1.4.5_beta3.alfredworkflow, the cancel now explicitly causes an abort (or at least it should) can you please give this a whirl and see how you go.

If it continues can you please capture the information from the "All Information" debug log on the workflow in Alfred and paste it here (just double check to make sure no private information is in it before you paste in).
Cheers,
Stuart

**Comment by stuartcryan** [comment]
Also, if it does continue, can you please confirm if you get the same loop on the "lplogin" command (I am assuming you would but would like to be sure).

**Comment by krokofant** [comment]
Awesome! Now it works!

**Comment by stuartcryan** [comment]
Excellent, glad we could get that fixed up. I will package it up and do a release shortly.

OOH and I always throw this at the end of my support tickets, if you love the workflow, my help etc it would be awesome if at some point you could donate towards getting me some cake and Diet Coke (haha it keeps me programming). Donations of course not required, only if you would like, love the workflow and have the means to do so.

https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=JM6E65M2GLXHE

Cheers,
Stuart
